---

baseurl:        "https://blog.elao.com/"
languageCode:   "fr-FR"
title:          "Le blog de la team ELAO"
Paginate:       10
#log:            true
#logFile:        "/var/log/hugo/hugo.log"
# verbose output
#verbose:                    true
# verbose logging
#verboseLog:                 true

params:
  Subtitle: "ELAO - Agence Web, Experts Symfony et Technologies Open Source - PARIS / LYON / MONTPELLIER"
  AuthorName: "ELAO"
  TwitterUser: "Elao"

taxonomies:
  tag:      "tags"
  category: "categories"
  author:   "authors'"

menu:
  main:
      # INFRA
      - Name:       "Infra"
        Identifier: "infra"
        URL:        "/infra"
        Weight:     200
      - Name:       "Proxmox"
        Identifier: "proxmox"
        URL:        "/categories/proxmox"
        Weight:     10
        parent:     "infra"
      - Name:       "Nginx"
        Identifier: "nginx"
        URL:        "/categories/nginx"
        Weight:     20
        parent:     "infra"
      - Name:       "Linux"
        Identifier: "linux"
        URL:        "/categories/linux"
        Weight:     30
        parent:     "infra"
      - Name:       "Monitoring"
        Identifier: "monitoring"
        URL:        "/categories/monitoring"
        Weight:     30
        parent:     "infra"

      # DEV
      - Name:       "Dev"
        Identifier: "dev"
        URL:        "/dev"
        Weight:     220
      - Name:       "Symfony"
        Identifier: "Symfony"
        URL:        "/categories/symfony"
        Weight:     10
        parent:     "dev"
      - Name:       "Web"
        Identifier: "web"
        URL:        "/categories/web"
        Weight:     20
        parent:     "dev"
      - Name:       "Conférences"
        Identifier: "conferences"
        URL:        "/categories/conférences"
        Weight:     30
        parent:     "dev"
      - Name:       "Javascript"
        Identifier: "javascript"
        URL:        "/categories/javascript"
        Weight:     40
        parent:     "dev"
      - Name:       "NodeJS"
        Identifier: "nodejs"
        URL:        "/categories/nodejs"
        Weight:     50
        parent:     "dev"
      - Name:       "PHP"
        Identifier: "php"
        URL:        "/categories/php"
        Weight:     60
        parent:     "dev"
      # TECH
      - Name:       "Tech"
        Identifier: "tech"
        URL:        "/tech"
        Weight:     230
      - Name:       "OSX"
        Identifier: "osx"
        URL:        "/categories/osx"
        Weight:     10
        parent:     "tech"
      # MISC
      - Name:       "Autour d'ELAO"
        Identifier: "elao"
        URL:        "/elao"
        Weight:     240
      - Name:       "Vie au bureau"
        Identifier: "vie-au-bureau"
        URL:        "/categories/vie-au-bureau"
        Weight:     10
        parent:     "elao"
      - Name:       "Communication/Conférences"
        Identifier: "communication"
        URL:        "/categories/communication"
        Weight:     30
        parent:     "elao"
      - Name:       "Actualités"
        Identifier: "actualites"
        URL:        "/categories/actualites"
        Weight:     40
        parent:     "elao"


      # ACTU
      #- Name:       "Actualités"
      #  Identifier: "news"
      #  URL:        "/news"
      #  Weight:     200
      #- Name:       "Vie au bureau"
      #  Identifier: "vie-au-bureau"
      #  URL:        "/categories/vie-au-bureau"
      #  Weight:     10
      #  parent:     "news"
      #- Name:       "Évènements"
      #  Identifier: "evenements"
      #  URL:        "/categories/evenements"
      #  Weight:     20
      #  parent:     "news"

