---

baseurl:        "http://blog.elao.dev/"
languageCode:   "fr-FR"
title:          "Le blog de la team ELAO"
Paginate:       10
log:            true
logFile:        "/var/log/hugo/hugo.log"
# verbose output
verbose:                    true
# verbose logging
verboseLog:                 true

params:
  Subtitle: "ELAO - Agence Web, Experts Symfony et Technologies Open Source - PARIS / LYON / MONTPELLIER"
  AuthorName: "ELAO"
  TwitterUser: "Elao"

taxonomies:
  tag:      "tags"
  category: "categories"
  author:   "authors'"

menu:
  main:
      # INFRA
      - Name:       "Infra"
        Identifier: "infra"
        URL:        "/infra"
        Weight:     200
      - Name:       "Proxmox"
        Identifier: "proxmox"
        URL:        "/categories/proxmox"
        Weight:     10
        parent:     "infra"
      - Name:       "OpenVZ"
        Identifier: "openvz"
        URL:        "/categories/openvz"
        Weight:     20
        parent:     "infra"
      - Name:       "Linux"
        Identifier: "linux"
        URL:        "/categories/linux"
        Weight:     30
        parent:     "infra"
      # DEV
      - Name:       "Dev"
        Identifier: "dev"
        URL:        "/dev"
        Weight:     220
      - Name:       "Web"
        Identifier: "web"
        URL:        "/categories/web"
        Weight:     10
        parent:     "dev"
      - Name:       "Conférences"
        Identifier: "conferences"
        URL:        "/categories/conferences"
        Weight:     20
        parent:     "dev"
      - Name:       "Javascript"
        Identifier: "javascript"
        URL:        "/categories/javascript"
        Weight:     30
        parent:     "dev"
      - Name:       "NodeJS"
        Identifier: "nodejs"
        URL:        "/categories/nodejs"
        Weight:     40
        parent:     "dev"
      # ACTU
      - Name:       "Actualités"
        Identifier: "actu"
        URL:        "/actu"
        Weight:     200
      - Name:       "Vie au bureau"
        Identifier: "vie-au-bureau"
        URL:        "/categories/vie-au-bureau"
        Weight:     10
        parent:     "actu"
      - Name:       "Évènements"
        Identifier: "evenements"
        URL:        "/categories/evenements"
        Weight:     20
        parent:     "actu"

  sidebar:
      - Name:       "Mon lien 1"
        Identifier: "mon-lien-1"
        URL:        "/about/mon-lien-1"
      - Name:       "Mon lien 2"
        Identifier: "mon-lien-2"
        URL:        "/about/mon-lien-2"
      - Name:       "Mon lien 3"
        Identifier: "mon-lien-3"
        URL:        "/about/mon-lien-3"
