---

_vendor:   elao
_app:      blog
_app_dir:  /srv/app/
_app_host: "{{ _app ~ ('.' ~ _vendor if _vendor else '') }}"

_user: vagrant
_env:  dev

_nginx_access_log: "{{ elao_nginx_log_dir }}/app.access.log"
_nginx_error_log:  "{{ elao_nginx_log_dir }}/app.error.log"
_nginx_logformat: '[$time_local] "request_method": $request_method "request_uri": $request_uri "status": $status "forward_from": $remote_addr "real_ip": "$http_x_forwarded_for" "body_bytes_sent": $body_bytes_sent "http_referer": $http_referer "user_agent": "$http_user_agent" "http_x_forwarded_proto": $http_x_forwarded_proto "request_time": $request_time "upstream_response_time": $upstream_response_time'

########
# Motd #
########

elao_motd_template: template/elao.j2
elao_motd:          California - 1993

############
# Timezone #
############

elao_timezone: Etc/UTC

#######
# Env #
#######

elao_env:
  - SYMFONY_ENV: "{{ _env }}"

#######
# Apt #
#######

elao_apt_update: true

elao_apt_repositories: []

elao_apt_preferences:
  - ruby@bearstech
  - git@debian_backports
  - file: dotdeb
    template: preferences/dotdeb_low.j2
  - nginx@nginx
  - nodejs@nodesource_0_12

elao_apt_packages:
  - name: golang
  - name: optipng
  - name: libjpeg-progs
  - name: graphicsmagick-imagemagick-compat

#######
# Ssh #
#######

elao_ssh_config_sshd_template: config/sshd/{{ _env }}.j2

elao_ssh_config_template: config/{{ _env }}.j2

elao_ssh_config:
  # Prod
  - Host *.elao.local:
    - User:                  deploy
    - ProxyCommand:          ssh gateway@hv-1.elao.com "nc %h %p"
    - ForwardAgent:          true
    - StrictHostKeyChecking: false
    - HashKnownHosts:        false

#######
# Git #
#######

elao_git_config_template: config/{{ _env }}.j2

#############
# Oh my zsh #
#############

elao_ohmyzsh_users:
  - user:     "{{ _user }}"
    template: users/{{ _env }}.j2
    config:
      - |
        elao_php_xdebug () {
            if [[ $1 == on ]]; then sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini.off /etc/php5/fpm/conf.d/20-xdebug.ini
            else sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini /etc/php5/fpm/conf.d/20-xdebug.ini.off; fi
            sudo service php5-fpm restart
        }
      - cd {{ _app_dir }}

#########
# Files #
#########

elao_files: ~

###############
# Mailcatcher #
###############

elao_mailcatcher_config_template: config/{{ _env }}.j2

##########
# Log.io #
##########

#elao_logio_config_harvester:
#  - nodeName: App
#  - logStreams:
#    - nginx:
#      - "{{ elao_nginx_log_dir }}/app.access.log"
#      - "{{ elao_nginx_log_dir }}/app.error.log"

#########
# Nginx #
#########

elao_nginx_logrotate_template: logrotate/weekly_52.j2

elao_nginx_config_template: config/http_{{ _env }}.conf.j2
elao_nginx_config:
  - http:
    - log_format: "main '{{ _nginx_logformat }}'"

elao_nginx_configs_exclusive: true
elao_nginx_configs:
  # Gzip
  - file:     gzip
    template: configs/gzip_{{ _env }}.j2

  - file:     blog.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - listen:      "{{ ansible_eth1.ipv4.address }}:80"
      - server_name: "{{ _app_host }}.dev"
      - access_log:  "{{ elao_nginx_log_dir }}/app.access.log"
      - error_log:   "{{ elao_nginx_log_dir }}/app.error.log"
      - location /:
        - proxy_set_header: "Host $host"
        - proxy_set_header: "X-Real-IP $remote_addr"
        - proxy_pass:       "http://localhost:1313"

  - file:     static.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - listen:      "{{ ansible_eth1.ipv4.address }}:8001"
      - server_name: "{{ _app_host }}.dev"
      - root:        "{{ _app_dir }}/hugo/public"
      - access_log:  "{{ elao_nginx_log_dir }}/app.access.log"
      - error_log:   "{{ elao_nginx_log_dir }}/app.error.log"
      - charset:     "UTF-8"
      - location /: []

##########
# Log.io #
##########

elao_logio_config_harvester:
  - nodeName: App
  - logStreams:
    - nginx:
      - "{{ elao_nginx_log_dir }}/app.access.log"
      - "{{ elao_nginx_log_dir }}/app.error.log"

##############
# Supervisor #
##############

elao_supervisor_config_template: config/{{ _env }}.conf.j2

elao_supervisor_configs_exclusive: true
elao_supervisor_configs:
  - file:     inet-http-server.conf
    template: configs/inet_http_server_{{ _env }}.conf.j2
  - file:     app-worker-hugo.conf
    template: configs/program_{{ _env }}.conf.j2
    config:
      - hugo:
        - command:         make server-start-fr
        - directory:       "{{ _app_dir }}/hugo"
        - user:            "www-data"
        - autorestart:     true
        - stdout_logfile:  "{{ elao_supervisor_log_dir }}/hugo.log"
        - redirect_stderr: true
