---

_vendor:   elao
_app:      blog
_app_dir:  /srv/app
_app_host: "{{ _app ~ ('.' ~ _vendor if _vendor else '') }}"

_user: vagrant
_env:  dev

########
# Motd #
########

elao_motd_template: template/elao.j2
elao_motd:          California - 1993

############
# Timezone #
############

elao_timezone: Etc/UTC

#######
# Env #
#######

elao_env:
  - SYMFONY_ENV: "{{ _env }}"

#######
# Apt #
#######

elao_apt_update: true

elao_apt_repositories:
  - bearstech
  - backports
  - dotdeb
  - nginx

elao_apt_preferences:
  - ruby@bearstech
  - git@backports
  - file: dotdeb
    template: preferences/dotdeb_low.j2
  - nginx@nginx

elao_apt_packages: []

#######
# Git #
#######

elao_git_config_template: config/{{ _env }}.j2

#############
# Oh my zsh #
#############

elao_ohmyzsh_users:
  - user:     "{{ _user }}"
    template: users/{{ _env }}.j2
    config:
      - |
        elao_php_xdebug () {
            if [[ $1 == on ]]; then sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini.off /etc/php5/fpm/conf.d/20-xdebug.ini
            else sudo mv /etc/php5/fpm/conf.d/20-xdebug.ini /etc/php5/fpm/conf.d/20-xdebug.ini.off; fi
            sudo service php5-fpm restart
        }
      - cd {{ _app_dir }}/symfony

#########
# Files #
#########

elao_files: ~

###############
# Mailcatcher #
###############

elao_mailcatcher_config_template: config/{{ _env }}.j2

##########
# Log.io #
##########

elao_logio_config_harvester:
  - nodeName: App
  - logStreams:
    - nginx:
      - "{{ elao_nginx_log_dir }}/app.access.log"
      - "{{ elao_nginx_log_dir }}/app.error.log"

#########
# Nginx #
#########

elao_nginx_config_template: config/http_{{ _env }}.conf.j2

elao_nginx_configs_exclusive: true
elao_nginx_configs: ~

##############
# Supervisor #
##############

elao_supervisor_config_template: config/{{ _env }}.conf.j2

elao_supervisor_configs_exclusive: true
elao_supervisor_configs: ~


